version: '3.4'
services:
  snippetbox:
    restart: always
    environment:
      CONN: "postgresql://host.docker.internal/snippetbox?user=postgres&password=dockermocker"
    depends_on:
      - snippetboxdb
    ports:
      - "4000:4000"
    build:
      dockerfile: Dockerfile
      context: .
  snippetboxdb:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dockermocker\
      POSTGRES_DB: snippetbox
    ports:
      - "5432:5432"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/init.sql